Repository AIBootcamp13/upstageailab-cv-classification-cv_5, pull requests merged in 2025-07, with the labels that each got.

#12 docs : Analysis of Prior Studies on Document Classification Using the LayoutLMv2 Model
  docs/using_LayoutLMV2_조사.md
Labels: 문서, 자료조사

#18 Train, Test data EDA
  codes/augment_exp.ipynb
  codes/eda.ipynb
  docs/Dataset EDA.md
  docs/images/test_aspect.png
  docs/images/test_blur.png
  docs/images/test_bright.png
  docs/images/test_colorchannel.png
  docs/images/test_contrast.png
  docs/images/test_noise.png
  docs/images/test_rotation.png
  docs/images/train_aspect.png
  docs/images/train_blur.png
  docs/images/train_bright.png
  docs/images/train_colorchannel.png
  docs/images/train_contrast.png
  docs/images/train_noise.png
  docs/images/train_rotation.png
  pyproject.toml
Labels: 문서, 개발, 진행 중

#21 fix: fix image url of 'Dataset EDA.md'
  docs/Dataset EDA.md
Labels: 버그, 문서

#23 feat: Add Augmentation Code To Address Class Imbalance
  codes/ahyeon/Baseline_augment_with_train_dataset_augmentation.ipynb
Labels: 문서, 개발

#29 New Baseline Completed
  .gitignore
  codes/Baseline_Gemini.ipynb
  codes/config.yaml
  codes/gemini_augmentation.py
  codes/gemini_evalute.py
  codes/gemini_main.py
  codes/gemini_train.py
  codes/gemini_utils.py
  docs/OOM_resolve.md
  docs/timm_model-name_convention.md
  pyproject.toml
Labels: 개발, 설정

#33 fix: file extension name fixed
  codes/Baseline_Gemini.ipynb
  codes/gemini_main.py
Labels: 버그

#38 Augmentation 전략 강화
  codes/config_v2.yaml
  codes/gemini_augmentation_v2.py
  codes/gemini_evalute_v2.py
  codes/gemini_main_v2.py
  codes/gemini_train_v2.py
  codes/gemini_utils_v2.py
Labels: 개발, 설정

#39 Dropout 전략 강화
  codes/config_v2.yaml
  codes/gemini_evalute_v2.py
  codes/gemini_main_v2.py
  codes/gemini_train_v2.py
  codes/gemini_utils_v2.py
Labels: 개발

#42 feat: update many.
  codes/config_v2.yaml
  codes/gemini_augmentation_v2.py
  codes/gemini_main_v2.py
  codes/gemini_train_v2.py
  codes/gemini_utils_v2.py
  data/train0705a.csv
Labels: 개발

#46 feat: update version 2.2
  codes/config_v2_2.yaml
  codes/gemini_augmentation_v2_2.py
  codes/gemini_evalute_v2_2.py
  codes/gemini_main_v2_2.py
  codes/gemini_train_v2_2.py
  codes/gemini_utils_v2_2.py
Labels: 버그, 개발

#47 feat: Gemini_v2_1 Codes Upload
  codes/config_v2_1.yaml
  codes/gemini_augmentation_v2_1.py
  codes/gemini_evalute_v2_1.py
  codes/gemini_main_v2_1.py
  codes/gemini_train_v2_1.py
  codes/gemini_utils_v2_1.py
Labels: 개발

#49 Update V2.2, V3
  codes/config_v2_2.yaml
  codes/config_v3_modelA.yaml
  codes/config_v3_modelB.yaml
  codes/delete_augmented_validation.ipynb
  codes/gemini_augmentation_v2_2.py
  codes/gemini_augmentation_v3.py
  codes/gemini_evalute_v2_2.py
  codes/gemini_evalute_v3.py
  codes/gemini_main_v2_2.py
  codes/gemini_main_v3.py
  codes/gemini_train_v2_2.py
  codes/gemini_train_v3.py
  codes/gemini_utils_v2_2.py
  codes/gemini_utils_v3.py
Labels: 개발
